### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by KulaGGin** [rm-NoobInCoding/UnrealReZen#25]
I have an 11.5 GB pakchunk0-Windows.ucas and after I pressed `Unpack ALL Files` button, UI froze immediately and now it's been working for around 30 minutes with no progress indicator.

It would be nice to add a progress indicator: 
• How many files total in the pakchunk and how many files it already unpacked.
• And also indicator in the sizes: total size of all files in the pakchunk and the size of all files it unpacked.

So we can see the progress in either file numbers or file sizes and see approximately how much it really unpacked and how much is left.

Also add the ability to cancel the unpacking and packing progress and not hang the UI.

**Comment by rm-NoobInCoding** [comment]
I am currently working on a new version of the tool that will rewrite a lot of the previous code and have a better ui. This is the reason why the project has not been updated for while (despite the bug reports).
Also this feature will be included in the next version

**Comment by KulaGGin** [comment]
I see. Thanks for answering. Can I find you somewhere to talk in real-time? Like, Discord, for example? I could implement those features in the new version.

**Comment by rm-NoobInCoding** [comment]
Send your discord username i will send a massage

**Comment by KulaGGin** [comment]
kulaggin
