### ISSUE TITLE
Unhandled exception trying to debug the application

### ISSUE THREAD

**Issue by KulaGGin** [rm-NoobInCoding/UnrealReZen#26]
After cloning the repo and then building the project, when I press Debug-Start Debugging, I get the unhandled exception error:
```
System.IO.FileLoadException: 'Could not load file or assembly 'System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
```
![devenv_EranptEowD](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/16989713/8dc3e160-65e2-4045-b63d-b28ad01a86a5)

**Comment by rm-NoobInCoding** [comment]
The tool has been updated to the new version and due to many changes, the previous issues have probably been solved by now (see readme). If you still have a problem, create a new issue
