### ISSUE TITLE
Unhandled exception when trying to pack empty .uasset file

### ISSUE THREAD

**Issue by KulaGGin** [rm-NoobInCoding/UnrealReZen#30]
After pressing on Repack Files button, when it repacks all the files, in the UEcastocLib.Packer.PackFilesToUcas method, when it encounters an empty file, it will throw an exception when trying to create a memory mapped file for it:
```
System.ArgumentException: 'A positive capacity must be specified for a Memory Mapped File backed by an empty file.'
```

![image](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/16989713/ab0e56d0-8a98-4f10-94de-30142016014a)

The file in question and the manifest:
[pakchunk0-Windows_Export_2.zip](https://github.com/rm-NoobInCoding/UnrealUnZen/files/13501036/pakchunk0-Windows_Export_2.zip)

The solution is probably to just use FileStream instead of MemoryMappedFile to read and write from the file.

**Comment by rm-NoobInCoding** [comment]
The tool has been updated to the new version and due to many changes, the previous issues have probably been solved by now (see readme). If you still have a problem, create a new issue
