### ISSUE TITLE
INI file extraction

### ISSUE THREAD

**Issue by Joshaze** [rm-NoobInCoding/UnrealReZen#33]
Will this tool extract INI files? When I search PAK archives and use the filter "{}.ini" or "{}.INI" it always extracts 0 files. Is this because the archives I'm loading don't include any of these files or does the tool not support extraction of these file types?

**Comment by Aeyth8** [comment]
Just use Fmodel

**Comment by rm-NoobInCoding** [comment]
The tool has been updated to the new version and due to many changes, the previous issues have probably been solved by now (see readme). If you still have a problem, create a new issue
