### ISSUE TITLE
Still not working.

### ISSUE THREAD

**Issue by switterbeet** [rm-NoobInCoding/UnrealReZen#34]
I tried this tool some months ago and it just never worked. unpacking assets worked but some utocs just give an error while others dont. Then when i want to repack it tells me it cant repack when the file already exists even when i chose a brand new utoc name.
It also doesnt unpack the assets with the folder structure like uecastoc does it.

How the heck is this supposed to even be useful?

After multiple months still no documentation or guide how to really use it either.

**Comment by rm-NoobInCoding** [comment]
Sorry for my late reply

Yes, I agree. Since working with UE structures can have specific structures based on each game, I plan to use the CUE4Parse library in the next update.

**Comment by 4rtb** [comment]
Try it as an analogue of this tool:  https://forums.unrealengine.com/t/how-to-extract-ucas-and-utoc-io-store-container-files-in-unreal-engine-5/1359694/2

**Comment by Real-N34r** [comment]
Off topic but it's related to modding , does anyone knows how to repack the Android game assets generally the(.obb) file ?

**Comment by rm-NoobInCoding** [comment]
> Try it as an analogue of this tool: https://forums.unrealengine.com/t/how-to-extract-ucas-and-utoc-io-store-container-files-in-unreal-engine-5/1359694/2

This way needs an installed version of UE
And many users can't or don't want to do this.

**Comment by 4rtb** [comment]
I think the best thing to use is the fmodel

**Comment by 4rtb** [comment]
fmodel will even be better than the first method that I sent, as for me

**Comment by 4rtb** [comment]
https://github.com/rm-NoobInCoding/UnrealUnZen/issues/36#issuecomment-2002066950 - best method for ue4 and ue5
(for ue4 games you dont need mapping files)

**Comment by rm-NoobInCoding** [comment]
The tool has been updated to the new version and due to many changes, the previous issues have probably been solved by now (see readme). If you still have a problem, create a new issue
