### ISSUE TITLE
How do I unpack .ucas files?

### ISSUE THREAD

**Issue by AngelWarrior123** [rm-NoobInCoding/UnrealReZen#36]
I know how to unpack .utoc files but how do I unpack .ucas files?

**Comment by 4rtb** [comment]
Check this: https://forums.unrealengine.com/t/how-to-extract-ucas-and-utoc-io-store-container-files-in-unreal-engine-5/1359694/2

**Comment by AngelWarrior123** [comment]
> Check this: https://forums.unrealengine.com/t/how-to-extract-ucas-and-utoc-io-store-container-files-in-unreal-engine-5/1359694/2

It works thanks for the reply :) do you by any chance know how I can import .uexp/.ubulk/.umap files into my own unreal project?

**Comment by 4rtb** [comment]
The moderator of the Fmodel (a program for unpacking UE game files) Discord server advised me not to unpack UCAS. Instead, I should use Fmodel, which utilizes UTOC to unpack it. By doing so, I can open and export everything (provided I have the correct mappings and Binkadecoder in the Fmodel folder).

**Comment by 4rtb** [comment]
So the best solution would be to just use fmodel

**Comment by 4rtb** [comment]
P.S. https://fmodel.app/
https://discord.com/invite/fdkNYYQ
Binkadecoder (put it in Output/.data folder of fmodel): https://cdn.discordapp.com/attachments/1090611236045062175/1203262911838158919/binkadec.exe?ex=6607d3e9&is=65f55ee9&hm=0c984e8cd2bb12d16121bfcd35357161e7cc355fe2e696e383f9a0310c52f918&
Binka is a ue audio format (like wav, it is only encrypted and, accordingly, a decoder is needed to open it)

**Comment by 4rtb** [comment]
![Screenshot_1](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/141040913/219aa23a-7658-4358-b956-338812a23474)

**Comment by AngelWarrior123** [comment]
Ill lay out the situation so basiclly this

> P.S. https://fmodel.app/ https://discord.com/invite/fdkNYYQ Binkadecoder (put it in Output/.data folder of fmodel): https://cdn.discordapp.com/attachments/1090611236045062175/1203262911838158919/binkadec.exe?ex=6607d3e9&is=65f55ee9&hm=0c984e8cd2bb12d16121bfcd35357161e7cc355fe2e696e383f9a0310c52f918& Binka is a ue audio format (like wav, it is only encrypted and, accordingly, a decoder is needed to open it)

Where is the Output/.data folder of Fmodel?

**Comment by AngelWarrior123** [comment]
The game that I have been trying to export files from comes with 5 files a UCAS file which contains .uexp/.ubulk/.uheader files, a UTOC file which contains pretty much only .uasset files, and a PAK file which contains only like font files. I have been trying to figure out a way to import these files into my project but haven't been able too. 
![Screenshot 2024-03-16 104751](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/72359784/8f5bc89d-0fff-4623-b21e-06d0485292fa)

**Comment by 4rtb** [comment]
![Screenshot_1](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/141040913/200c3e8f-80bc-473d-bb14-f37c062bff73)
![Screenshot_2](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/141040913/e045ffde-8156-4585-b2d6-98fd0e833d63)
(You have to open the fmodel for these folders to appear)

**Comment by 4rtb** [comment]
And about the mappings: you can try to find them on the fmodel server for your game or generate them yourself

**Comment by 4rtb** [comment]
> The game that I have been trying to export files from comes with 5 files a UCAS file which contains .uexp/.ubulk/.uheader files, a UTOC file which contains pretty much only .uasset files, and a PAK file which contains only like font files. I have been trying to figure out a way to import these files into my project but haven't been able too. ![Screenshot 2024-03-16 104751](https://private-user-images.githubusercontent.com/72359784/313421967-8f5bc89d-0fff-4623-b21e-06d0485292fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTIwNjIsIm5iZiI6MTcxMDYxMTc2MiwicGF0aCI6Ii83MjM1OTc4NC8zMTM0MjE5NjctOGY1YmM4OWQtMGZmZi00NjIzLWIyMWUtMDZkMDQ4NTI5MmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZWIyMWI1OGIwYTRhZDczMTk0OTJkZmJjZGRjMTc3ODc3ODY0MGM3ZWU3Mjk0ZDgzNDUyMjMyMWU4YzdlYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cowFqhdRCc7t2IR-6oj8ib9iXWNKL8BvoH1sKm_Y8rg)

just use fmodel

**Comment by 4rtb** [comment]
https://github.com/TheNaeem/UnrealMappingsDumper (you need inject dll file to program to get mappings, you can use extreme injector or process hacker as injector) or
https://github.com/UE4SS-RE/RE-UE4SS (https://docs.ue4ss.com/dev/feature-overview/dumpers.html#usmap-dumper (usage guide), https://www.youtube.com/watch?v=TytHkZ7R0jQ (installation guide)

**Comment by 4rtb** [comment]
![Screenshot_3](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/141040913/1ca16aaa-7824-4c22-845c-382db69ce141)
P.S. If you can't find the file, then you can use the everything program to do this: https://www.voidtools.com/

**Comment by AngelWarrior123** [comment]
Im able to extract 

> Two methods: https://github.com/TheNaeem/UnrealMappingsDumper (you need inject dll file to program to get mappings, you can use extreme injector or process hacker as injector) or https://github.com/UE4SS-RE/RE-UE4SS (https://docs.ue4ss.com/dev/feature-overview/dumpers.html#usmap-dumper (usage guide), https://www.youtube.com/watch?v=TytHkZ7R0jQ (installation guide)

Where do I inject the DLL file to?

**Comment by AngelWarrior123** [comment]
Do i inject it into the game Im trying to take files from?

**Comment by AngelWarrior123** [comment]
Ok i got it to work. and I have the Mappings.usmap file. What do I do with it?
![Screenshot 2024-03-16 111737](https://github.com/rm-NoobInCoding/UnrealUnZen/assets/72359784/e2f73140-185b-403d-a24c-bdc183076436)

**Comment by 4rtb** [comment]
Yes, or use ue4ss as a dll inject mapping creation analog (by the way, the injection method did not always work for me (generated non-working maps (it can be calculated by their very small size and when opened in notepad there is very little or no text there)) and I used ue4ss)

**Comment by 4rtb** [comment]
I will record video for you

**Comment by AngelWarrior123** [comment]
> Yes, or use ue4ss as a dll inject mapping creation analog (by the way, the injection method did not always work for me (generated non-working maps (it can be calculated by their very small size and when opened in notepad there is very little or no text there)) and I used ue4ss)

I opened the usmap filke in notepad and it had ALOT of text it was all symbols though. I think it worked

**Comment by 4rtb** [comment]
https://www.veed.io/view/ca79362c-554f-4ad6-8030-a2bff9fec735?panel=share
You can use my mappings for backrooms games: https://discord.gg/pUYMC2A5...
P.S. Complex uses mixamo animations so you don't have to export them I think.

**Comment by 4rtb** [comment]
https://www.veed.io/view/98fb865f-ec6a-4e3b-9079-d535bec6b9b5?panel=share (how to preview model animation in fmodel)

**Comment by 4rtb** [comment]
d

> > Yes, or use ue4ss as a dll inject mapping creation analog (by the way, the injection method did not always work for me (generated non-working maps (it can be calculated by their very small size and when opened in notepad there is very little or no text there)) and I used ue4ss)
> 
> I opened the usmap filke in notepad and it had ALOT of text it was all symbols though. I think it worked

yes, its good mapping

**Comment by AngelWarrior123** [comment]
> https://www.veed.io/view/ca79362c-554f-4ad6-8030-a2bff9fec735?panel=share You can use my mappings for backrooms games: https://discord.gg/pUYMC2A5... P.S. Complex uses mixamo animations so you don't have to export them I think.

I really appreciate you making a video :) Is there a way to be able to export the materials (A post process material for example) and import that into my project?

**Comment by 4rtb** [comment]
Btw, here is this hazmat (with different types of textures) and other... https://drive.google.com/drive/folders/1bIwIbWlxw1cwQOJ639zvX6nfXmDdSveD?usp=drive_link
https://drive.google.com/file/d/18d3lCVQHaVJrTtSJFSLyQqzZOupWwrvb/view?usp=drive_link

**Comment by rm-NoobInCoding** [comment]
The tool has been updated to the new version and due to many changes, the previous issues have probably been solved by now (see readme). If you still have a problem, create a new issue
