### ISSUE TITLE
asset creation

### ISSUE THREAD

**Issue by Real-N34r** [rm-NoobInCoding/UnrealReZen#38]
![image](https://github.com/user-attachments/assets/f1c48462-b48d-4105-885b-c09440278739)
![image](https://github.com/user-attachments/assets/db5443ca-cfbe-4d93-b54a-f83b75ace90e)

the files it generates are only 1 kb .Why? even when i used compression none

**Comment by rm-NoobInCoding** [comment]
Maybe because you are packing only three asset?

**Comment by Real-N34r** [comment]
> Maybe because you are packing only three asset?

Does the tool encrypt the file with the provided aes key?
Cause when i try to open the patch files there is a red mark in fmodel

**Comment by rm-NoobInCoding** [comment]
Yes but encrypting is experimental.
Also because i set the PerfectHashCount to zero in patched utoc, FModel refuse to load it.
Im still working on this

**Comment by switterbeet** [comment]
I have the same problem and also Fmodel cannot read my mod which is a sign that it didnt work. 
![Screenshot 2024-09-15 112316](https://github.com/user-attachments/assets/f67c7cf2-0158-4bc9-83bf-9ae4430102d5)
And my game crashes with: 

![image2110](https://github.com/user-attachments/assets/f6d32432-5521-478f-a239-a3f19c85b923)

Log is (almost) fine: 

![Screenshot 2024-09-15 112736](https://github.com/user-attachments/assets/91dc73d0-ae25-4a0c-93c4-78924a8efccf)

**Comment by rm-NoobInCoding** [comment]
Please upload your utoc and ucas

**Comment by Real-N34r** [comment]
> Please upload your utoc and ucas

My patch also didn't work!!
Here's my files with aes key 
https://drive.google.com/file/d/1Oi-S1VUHVfazuE9Z9E0QjQidfL76Bz48/view?usp=drivesdk

**Comment by rm-NoobInCoding** [comment]
Add "_P" to the end of your file names.
if that didn't worked. upload one origianl utoc + ucas file

**Comment by switterbeet** [comment]
> Please upload your utoc and ucas

[Blood_P.zip](https://github.com/user-attachments/files/17012105/Blood_P.zip)

**Comment by rm-NoobInCoding** [comment]
upload one original utoc + ucas file

**Comment by rm-NoobInCoding** [comment]
Because I didn't got any reply I assume that the problem is fixed. Feel free to reopen this issue or make another one if you have the problem

**Comment by Real-N34r** [comment]
> Because I didn't got any reply I assume that the problem is fixed. Feel free to reopen this issue or make another one if you have the problem 

I've uploaded the original ucas and utoc as you said

**Comment by rm-NoobInCoding** [comment]
> > Because I didn't got any reply I assume that the problem is fixed. Feel free to reopen this issue or make another one if you have the problem
> 
> I've uploaded the original ucas and utoc as you said
Can you make another issue with the bug template? I can help you better in that way
