### ISSUE TITLE
Error: Output path must contain .utoc extension even tho it has it included

### ISSUE THREAD

**Issue by switterbeet** [rm-NoobInCoding/UnrealReZen#39]
![grafik](https://github.com/user-attachments/assets/7369f7de-c819-4e1c-89d1-db7b322392f9)

I get that error even tho my path has .utoc included

This is my full command: UnrealReZen.exe --content-path X:\SteamLibrary\steamapps\common\LOLLIPOP CHAINSAW RePOP\lollipop\Content\Paks\Blood_P --compression-format Zlib --engine-version GAME_UE5_3 --game-dir X:\SteamLibrary\steamapps\common\LOLLIPOP CHAINSAW RePOP\lollipop\Content\Paks  --output-path X:\SteamLibrary\steamapps\common\LOLLIPOP CHAINSAW RePOP\lollipop\Content\Paks\Blood_P.utoc

**Comment by rm-NoobInCoding** [comment]
All of you paths contains space ' ' character. Please use double quotation " before and after the paths

For example:
`UnrealReZen.exe --content-path "X:\SteamLibrary\steamapps\common\LOLLIPOP CHAINSAW RePOP\lollipop\Content\Paks\Blood_P" --compression-format Zlib --engine-version GAME_UE5_3 --game-dir "X:\SteamLibrary\steamapps\common\LOLLIPOP CHAINSAW RePOP\lollipop\Content\Paks" --output-path "X:\SteamLibrary\steamapps\common\LOLLIPOP CHAINSAW RePOP\lollipop\Content\Paks\Blood_P.utoc"`

**Comment by switterbeet** [comment]
Thanks!!
