### ISSUE TITLE
How to edit unpacked uasset?

### ISSUE THREAD

**Issue by skyfony** [rm-NoobInCoding/UnrealReZen#41]
[DELETED]

**Comment by skyfony** [comment]
> It was a example and i just Hex-Changed some bytes. afaik there is no tool for editing its assets without mapping.

Can u explain what do u mean by "without mapping" please?

**Comment by rm-NoobInCoding** [comment]
Each ue5 game have its own mapping structure for assets.
FModel supports custom mapping. you can get mapping file for many games in FModel discord server.

**Comment by skyfony** [comment]
Yea, I know that. And I'm using mapping file in Fmodel, but UAssetGUI can't edit uasset even after I connected UAssetGUI to mapping file. Do u know any toold that can edit Zen uasset if I have mapping file? Let me know, please. Because I know only about UAssetGUI tool.

**Comment by rm-NoobInCoding** [comment]
The best option is still UAssetGUI, I dunno if they have a discord server but afaik they answer quickly in emails (hello@atenfyr.com)

**Comment by skyfony** [comment]
> The best option is still UAssetGUI, I dunno if they have a discord server but afaik they answer quickly in emails ([hello@atenfyr.com](mailto:hello@atenfyr.com))

But we can't edit Zen uasset via UAssetGUI bro, what do I do then?

**Comment by rm-NoobInCoding** [comment]
At least contacting author is better option.
Besides I will take a look at it source to see what we can do for adding support of zen uassets.

**Comment by rm-NoobInCoding** [comment]
What assets so you want to edit?

**Comment by skyfony** [comment]
> What assets do you want to edit?
For example this one, I want to change some values to make modded camera in game
![25425](https://github.com/user-attachments/assets/a1484a33-c573-48b7-98ab-1f3d4258f49b)

**Comment by rm-NoobInCoding** [comment]
Currently you can change these values by Hex-Editing. There is no tool for parse the file.

**Comment by skyfony** [comment]
> ![image](https://private-user-images.githubusercontent.com/52470097/369919217-c4c163b6-e597-43b3-b779-898e431fba3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDU4NTAsIm5iZiI6MTcyNzEwNTU1MCwicGF0aCI6Ii81MjQ3MDA5Ny8zNjk5MTkyMTctYzRjMTYzYjYtZTU5Ny00M2IzLWI3NzktODk4ZTQzMWZiYTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MzIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZjk4ZmM5NmRmNTI5MjFlNjM2YzViNzFiZmM3Njk1ZmU2ZTQwNWE0YzhkNzZmNWI5N2NmOTBmZTMzYWUwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FplWeTouxqgxZr-5lulyLp6KOS801_RckrI92LsYgQw) Example value from your image in hex editor. (Пример значений как на твоём изображении в Hex редакторе) Search (Поиск) The values are mainly used in UE as below. (В основном используются в UE значения как ниже) ![image](https://private-user-images.githubusercontent.com/52470097/369920531-8f74a554-2721-407b-b2a1-0d5c7541ef09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDU4NTAsIm5iZiI6MTcyNzEwNTU1MCwicGF0aCI6Ii81MjQ3MDA5Ny8zNjk5MjA1MzEtOGY3NGE1NTQtMjcyMS00MDdiLWIyYTEtMGQ1Yzc1NDFlZjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MzIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTNlMWQ1NWM1ZmY1OGJjY2JjYjcyZTgwZGI5NzZmMTY5YmEwMTZkYzAyMThiNTI1NzEzYTIzNjhlYjgyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uCJ7GgghAEAX7f8Jn9O7aD0iVl24kyjhkryHIrPL3p8)
> 
> I can help you outside the Github. It is also possible to try to unpack and try to edit in the UAssetGUI itself and pack it after, but I'm not sure what will happen. Add me to the Discord and we'll write off. @TheDarkness_RU Могу помочь вне Github. Также возможно можно попробовать распаковать и попробовать отредактировать в самом UAssetGUI и после запаковать, но не уверен что получится. Добавь меня в Discord спишемся. @TheDarkness_RU

Отправил заявку
