### ISSUE TITLE
UTOC file extension not being recognized (Fatal Error)

### ISSUE THREAD

**Issue by SparklesRolf** [rm-NoobInCoding/UnrealReZen#43]
**Describe the bug**
UTOC extension in command isn't being recognized even though its present in the output path

**Tool outputs**
CMD
UnrealReZen.exe -c G:/Game Launchers/Steam/steamapps/common/LOCKDOWN Protocol/LockdownMods --compression-format Oodle -e GAME_UE5_2 -g G:/GameLaunchers/Steam/steamapps/common/LOCKDOWNProtocol/LockdownProtocol/Content/Paks -o G:/Game Launchers/Steam/steamapps/common/LOCKDOWN Protocol/LockdownProtocol/Content/Paks/MyPatch_P.utoc

Output
[20:02:55 FTL] Output path must contain utoc extension

**Expected behavior**
Tool to create patch files

**Game Name**
LOCKDOWN Protocol | Unreal 5.2

**Screenshots**
![CMD](https://github.com/user-attachments/assets/3d3eb7bc-f379-4732-8c63-a28bb965f793)
![GameFolder](https://github.com/user-attachments/assets/b913f49e-c155-45ad-90ff-9b3b2f0265ea)
![ModFolder](https://github.com/user-attachments/assets/efbb8786-a061-4057-8604-a8893b212681)

**Your patch files**
N/A

**Additional context**
Not about the problem but new to Unreal modding, could be doing something very wrong lol

**Comment by rm-NoobInCoding** [comment]
Hey,
Take a look at this issue #39

**Comment by skyfony** [comment]
> Hey, Take a look at this issue #39

Hey bro, I'm still waiting for ur answer in my ticket 🥺

**Comment by SparklesRolf** [comment]
epic, trying that out now <3
