### ISSUE TITLE
ZenTools IO Store dumps (uAsset + uEXP) unsupported

### ISSUE THREAD

**Issue by korgano** [rm-NoobInCoding/UnrealReZen#46]
**Describe the bug**
Generating patch mods with uAsset + uEXP pairs causes crashes when loading the game, presumably due to missing data.

**Expected behavior**
Generation of patch mod files that do not generate crashes.

**Game Name**
Aliens: Dark Descent, UE4.27

**Additional context**
uAsset + uEXP pairs generated with [ZenTools-UE4](https://github.com/WistfulHopes/ZenTools-UE4/releases/tag/ue4-1.0.2)

These pairs are the only way to allow people to mod uAssets from Zen IO store games in uAssetGUI, so they are **very** important to the modding community.

Zip contains sample uAsset + uEXP pairs for examination.
[MarineClasses.zip](https://github.com/user-attachments/files/17177046/MarineClasses.zip)

**Comment by rm-NoobInCoding** [comment]
As far as i know the ZenLoader is for uasset files (without uexp)
Are you sure that the game itself have uexp in ZenLoader archives?

**Comment by korgano** [comment]
All my ZenTools-UE4 dumps generate uAsset+uEXP pairs. The program is clearly getting some kind of data out of there, but I'm not sure how essential it is.

From what I can tell, Unreal Engine itself doesn't have issues with packing the uAssets by themselves into UTOC/UCAS, but I know uAssetGUI can't handle the uAssets without the uEXPs. IIRC, the Fmodel uAsset dumps basically combine the two into one file, which is what causes the compatibility issues with uAssetGUI.

**Comment by rm-NoobInCoding** [comment]
FModel just extracts the assets as they are in the original archive and my tool is based on that.
If the tool you are using is generating uexp, then you need to figure out how to convert it back.
